### ISSUE TITLE
Example Failed

### ISSUE THREAD

**Issue by nasyxx** [coady/lupyne#4]
It seems that example failed:

	lucene.initVM()
    indexer = engine.Indexer()
    indexer.set('name', stored=True)
    indexer.set('text')
    indexer.add(name='sample', text='hello world')
    indexer.commit()

Will raise:

```
Traceback (most recent call last):
  File "index.py", line 78, in <module>
    indexer.set('text')
  File "/Users/Nasy/.pyenv/versions/3.8.0/lib/python3.8/site-packages/lupyne/engine/indexers.py", line 546, in set
    field = self.fields[name] = cls(name, **settings)
  File "/Users/Nasy/.pyenv/versions/3.8.0/lib/python3.8/site-packages/lupyne/engine/documents.py", line 61, in __init__
    assert self.stored or self.indexed or self.docvalues or self.dimensions
AssertionError
```

**Comment by coady** [comment]
Looks like that's from an old version.  The [current example](https://github.com/coady/lupyne/blob/master/docs/index.rst#quickstart) is:
```
...
indexer.set('text', engine.Field.Text)
...
```

Lucene used to have default field settings.

**Comment by nasyxx** [comment]
Thanks!
